# Generated by Django 4.0.4 on 2022-10-26 00:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 0, 50, 26, 620087, tzinfo=utc), verbose_name='date published'),
        ),
    ]
