# Generated by Django 4.0.4 on 2022-10-29 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 5, 40, 48, 832701, tzinfo=utc), verbose_name='date published'),
        ),
    ]
